/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Aparna.Radhakrishna' at '24/10/15 13:03' with Gradle 1.12
 *
 * @author Aparna.Radhakrishna, @date 24/10/15 13:03
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
