import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Aparna.Radhakrishna' at '24/10/15 13:03' with Gradle 1.12
 *
 * @author Aparna.Radhakrishna, @date 24/10/15 13:03
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
